CREATE TABLE CURSO(
CODCURSO SERIAL PRIMARY KEY,
NOMECURSO VARCHAR (80) NOT NULL UNIQUE
);

CREATE TABLE SEXO(
CODSEXO SERIAL PRIMARY KEY,
NOMESEXO VARCHAR(9) NOT NULL UNIQUE
);
CREATE TABLE RUA(
CODRUA SERIAL PRIMARY KEY,
NOMERUA VARCHAR (80) NOT NULL UNIQUE
);
CREATE TABLE BAIRRO(
CODBAIRRO SERIAL PRIMARY KEY,
NOMEBAIRRO VARCHAR (80) NOT NULL UNIQUE
);
CREATE TABLE CEP(
CODCEP SERIAL PRIMARY KEY,
NUMEROCEP VARCHAR (80) NOT NULL UNIQUE
);
CREATE TABLE ESTADO(
CODESTADO SERIAL PRIMARY KEY,
NOMEESTADOSIGLA VARCHAR (2) NOT NULL UNIQUE
);
CREATE TABLE CIDADE(
CODCIDADE SERIAL PRIMARY KEY,
NOMECIDADE VARCHAR (80) NOT NULL UNIQUE,
CODESTADO_FK INTEGER REFERENCES ESTADO(CODESTADO)  ON
DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUNO(
CODALUNO SERIAL PRIMARY KEY,
NOMECALUNO VARCHAR (80) NOT NULL,
CODCURSO_FK INTEGER REFERENCES CURSO(CODCURSO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODSEXO_FK INTEGER REFERENCES SEXO(CODSEXO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODRUA_FK INTEGER REFERENCES RUA(CODRUA) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODBAIRRO_FK INTEGER REFERENCES BAIRRO(CODBAIRRO) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODCEP_FK INTEGER REFERENCES CEP(CODCEP) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE,

CODCIDADE_FK INTEGER REFERENCES CIDADE(CODCIDADE) MATCH SIMPLE ON
	DELETE CASCADE ON UPDATE CASCADE
);

--CURSO
INSERT INTO CURSO (NOMECURSO) VALUES('ADS');
INSERT INTO CURSO (NOMECURSO) VALUES('ENFERMAGEM');
INSERT INTO CURSO (NOMECURSO) VALUES('MEDICINA');
INSERT INTO CURSO(NOMECURSO) VALUES('AGRONOMIA')

SELECT * FROM CURSO;

--RUA
INSERT INTO RUA(NOMERUA) VALUES ('XX DOS SANTOS');
INSERT INTO RUA(NOMERUA) VALUES ('YY DAS MARGARIDAS');

SELECT * FROM RUA;

--BAIRRO
INSERT INTO BAIRRO(NOMEBAIRRO) VALUES ('CENTRO');
INSERT INTO BAIRRO(NOMEBAIRRO) VALUES ('ZONA SUL');

SELECT * FROM BAIRRO;

--ESTADO
INSERT INTO ESTADO(NOMEESTADOSIGLA) VALUES ('SP');
INSERT INTO ESTADO(NOMEESTADOSIGLA) VALUES ('MG');

SELECT * FROM ESTADO;

--CIDADE
INSERT INTO CIDADE(NOMECIDADE, CODESTADO_FK) VALUES ('SANTA FÉ DO SUL',1);
INSERT INTO CIDADE(NOMECIDADE, CODESTADO_FK) VALUES ('SÃO PAULO',1);
INSERT INTO CIDADE(NOMECIDADE, CODESTADO_FK) VALUES ('BRUMADINHO',2);

SELECT * FROM CIDADE;

--ALUNO
INSERT INTO ALUNO
(NOMECALUNO, CODSEXO_FK, CODCURSO_FK, CODRUA_FK,
CODBAIRRO_FK, CODCEP_FK, CODCIDADE_FK) VALUES
('MARCOS',1,2,2,1,1,3);
SELECT * FROM ALUNO;

SELECT * FROM CIDADE;

--SEXO
SELECT * FROM SEXO;
INSERT INTO SEXO
(NOMESEXO) VALUES ('MASCULINO');
INSERT INTO SEXO
(NOMESEXO) VALUES ('FEMININO');

--CEP
SELECT * FROM CEP;
INSERT INTO CEP
(NUMEROCEP) VALUES ('15775-000');
INSERT INTO CEP
(NUMEROCEP) VALUES ('01153-000');
INSERT INTO CEP
(NUMEROCEP) VALUES ('35460-000');
